### ISSUE TITLE
Tooltip backgrounds not appearing in Windows 10

### ISSUE THREAD

**Issue by stephensmith9** [AlbertBall/railway-dot-exe#1]
Tried to submit this using the contact form on the new website but I get errors after hitting submit so posting here, sorry if this is not the proper channel for the project...

Using Windows 10 Home Version 1709 OS Build 16299.192 and running v2.0.0 Beta of railway.exe. The floating window backgrounds (that appear when hovering over a train for example) are not appearing on the display. The text shows (the content) but there is no background behind it (which should be a pale yellow colour from what I see in the Help videos). The lack of a pale yellow background has the effect of making the text merge into the main screen display and difficult to read when it floats over track or other graphical & textual elements. I tried switching to the black background but then the text is completely unreadable as it remains in a black font. Not sure if this is an Embarcadero VCL control issue as a result of updating to the new C++ Builder?

I have the latest graphics drivers installed for an NVIDIA GeForce GTX 1060. Screen is 1920x1080, True Color (32bit), 60Hz.

**Comment by AlbertBall** [comment]
Hi Stephen,

The website is in the process of upgrading so that might have interfered
with your trying to send the message that way.  Another way to contact me
is via my ROS email which is railwayfeedback@gmail.com.

I feel sure the problem you describe is due to the program colour
limitations being misinterpreted by the later TruColor graphic handlers.
Oddly this has only surfaced with the later Embarcadero version - not sure
why that should be - but fortunately there is an easy fix.

Just right click on the program icon, select Properties and Compatibility,
then tick the 256 colours box. That should fix any problems and only needs
to be done once.

Regards,

Albert

**Comment by stephensmith9** [comment]
Awesome! Thanks Albert, that did the trick. Now that you mention it I recall seeing that somewhere on your site, I should have remembered that, sorry.

Regards,
Stephen.

**Comment by AlbertBall** [comment]
Hi Stephen,

Glad to hear the fix worked OK, thanks for letting me know.

Regards,

Albert
