### ISSUE TITLE
a question of the maxinum text of train ID

### ISSUE THREAD

**Issue by naruru** [AlbertBall/railway-dot-exe#4]
I am a Chinese train enthusiast and now I am using the Railway-dot-exe to build a complex railway system of a China city,
But now I am fact a problem,when I input the train ID like ‘C7001‘ or 'DJ7856' （in Chinese railway system that mean city-express EMU train and the high-speed railway checking train.）and they not fully show it （example 7001 or 7856，only 4 text）
How to support display more than 4 characters ？
Looking forward to your reply and please regret my poor English.

**Comment by AlbertBall** [comment]
Hi Naruru,

Your English is very good - a lot better than my Chinese!

Train identifiers in the timetable can be up to 8 characters long, but in
all cases only the last 4 characters are shown during operation. This
conforms to UK headcode practice but I'm aware that other countries use
different headcode lengths. Displayed trains occupy 2 elements, with 2
characters per element, so it isn't really possible to display more without
a major re-design of the program.

What I suggest is to use 5 character identifiers in the timetable, and to
include the full identifier in the train description, so that when the
mouse hovers over the train with train information showing the full
identifier can be seen. It's not ideal I know, but hopefully it will help
in your project.

I hope that idea is useful, and I hope you will consider adding your
project to the website when you're happy with it.

With best wishes for a successful project,

Albert
